export interface Fragment {
  url: string;
  duration: number;
}

export interface Format {
  format_id: string;
  format_note: string;
  ext: string;
  protocol: string;
  acodec: string;
  vcodec: string;
  url: string;
  width?: number;
  height?: number;
  fps?: number;
  rows: number;
  columns: number;
  fragments: Fragment[];
  audio_ext: string;
  video_ext: string;
  format: string;
  resolution: string;
  aspect_ratio?: number;
  asr?: number;
  filesize?: number;
  source_preference?: number;
  audio_channels?: number;
  quality?: number;
  has_drm?: boolean;
  tbr?: number;
  language?: any;
  language_preference?: number;
  preference?: number;
  dynamic_range: string;
  abr?: number;
  container: string;
  vbr?: number;
  filesize_approx?: number;
}

export interface Thumbnail {
  url: string;
  preference: number;
  id: string;
  height?: number;
  width?: number;
  resolution: string;
}

export interface RequestedFormat {
  asr?: number;
  filesize: number;
  format_id: string;
  format_note: string;
  source_preference: number;
  fps?: number;
  audio_channels?: number;
  height?: number;
  quality: number;
  has_drm: boolean;
  tbr: number;
  url: string;
  width?: number;
  language?: any;
  language_preference: number;
  preference?: any;
  ext: string;
  vcodec: string;
  acodec: string;
  dynamic_range: string;
  vbr: number;
  container: string;
  protocol: string;
  video_ext: string;
  audio_ext: string;
  format: string;
  resolution: string;
  aspect_ratio?: number;
  abr?: number;
}

export interface YtdlResponse {
  id: string;
  title: string;
  formats: Format[];
  thumbnails: Thumbnail[];
  thumbnail: string;
  description: string;
  uploader: string;
  uploader_id: string;
  uploader_url: string;
  channel_id: string;
  channel_url: string;
  duration: number;
  view_count: number;
  average_rating?: any;
  age_limit: number;
  webpage_url: string;
  categories: string[];
  tags: string[];
  playable_in_embed: boolean;
  live_status: string;
  release_timestamp?: any;
  _format_sort_fields: string[];
  comment_count?: any;
  chapters?: any;
  like_count: number;
  channel: string;
  channel_follower_count: number;
  upload_date: string;
  availability: string;
  original_url: string;
  webpage_url_basename: string;
  webpage_url_domain: string;
  extractor: string;
  extractor_key: string;
  playlist?: any;
  playlist_index?: any;
  display_id: string;
  fulltitle: string;
  duration_string: string;
  is_live: boolean;
  was_live: boolean;
  requested_subtitles?: any;
  _has_drm?: any;
  requested_formats: RequestedFormat[];
  format: string;
  format_id: string;
  ext: string;
  protocol: string;
  language?: any;
  format_note: string;
  filesize_approx: number;
  tbr: number;
  width: number;
  height: number;
  resolution: string;
  fps: number;
  dynamic_range: string;
  vcodec: string;
  vbr: number;
  stretched_ratio?: any;
  aspect_ratio: number;
  acodec: string;
  abr: number;
  asr: number;
  audio_channels: number;
}
